- name: Palo Alto Policy Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    palo_provider:
      ip_address: "{{ ansible_host }}"
      username: 'admin_rw'
      password: 'pass_admin_rw'
    search_rule_name: 'BGP'

  tasks:
    - name: Retrieve security rules
      panos_security_rule_info:
        provider: "{{ palo_provider }}"
        timeout: 120
      register: security_rules_info
      failed_when: security_rules_info is failed

    - name: Search for rule
      debug:
        msg: "Security rule '{{ search_rule_name }}' exists"
      when: security_rules_info.rules | selectattr('rule_name', 'search', search_rule_name) | list | count > 0
      ignore_errors: yes
