- name: Palo Alto Policy Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    palo_provider:
      ip_address: "{{ ansible_host }}"
      username: 'admin_rw'
      password: 'pass_admin_rw'

  tasks:
    - name: Change existing rule
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ palo_provider }}"
        rule_name: 'SERVER_1_DNS'
        application: 'ssl,dns'

    - name: Commit Configuration
      panos_commit_firewall:
        provider: '{{ palo_provider }}'
