- name: Palo Alto Policy Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    csv_file_path: "/Users/janblahuta/Documents/GitHub/PA-Automation/PaloAlto/PA-ANSIBLE-ACL-RULES/ansible.csv"
    palo_provider:
      ip_address: "{{ ansible_host }}"
      username: 'admin_rw'
      password: 'pass_admin_rw'

  tasks:
    - name: Load firewall rule variables from CSV
      set_fact:
        firewall_rules: "{{ lookup('csvfile', csv_file_path, delimiter=';', colnames=true) }}"
      ignore_errors: yes

    - name: Create firewall rules
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ palo_provider }}"
        name: "{{ item.name }}"
        source_zone: "{{ item.source_zone }}"
        destination_zone: "{{ item.destination_zone }}"
        source: "{{ item.source }}"
        destination: "{{ item.destination }}"
        application: "{{ item.application }}"
        action: "{{ item.action }}"
        log_start: "{{ item.log_start }}"
        log_end: "{{ item.log_end }}"
      loop: "{{ firewall_rules }}"
      ignore_errors: yes
