---

- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    palo_provider:
      ip_address: "{{ ansible_host }}"
      username: 'admin'
      password: 'Terezka30'

  tasks:

    - name: Create object 'HOST'
      panos_address_object:
        provider: '{{ ansible_host }}'
        name: 'SERVER_1'
        value: '10.10.10.100'
        description: 'Production-Server-1'