- name: Palo Alto Policy Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    csv_file_path: "/Users/janblahuta/Documents/GitHub/PA-Automation/PaloAlto/PA-ANSIBLE-ACL-RULES/ansible.csv"
    palo_provider:
      ip_address: "{{ ansible_host }}"
      username: 'admin_rw'
      password: 'pass_admin_rw'

  tasks:

    - name: Read firewall rules from CSV
      community.general.read_csv:
        path: "/Users/janblahuta/Documents/GitHub/PA-Automation/PaloAlto/PA-ANSIBLE-ACL-RULES-CSV/ansible.csv"
        key: name
      register: firewall_rules

    - name: Add security rule to Palo Alto firewall
      paloaltonetworks.panos.panos_security_rule:
        source_zone: "{{ item.source_zone }}"
        destination_zone: "{{ item.destination_zone }}"
        source: "{{ item.source }}"
        destination: "{{ item.destination }}"
        application: "{{ item.application }}"
        action: "{{ item.action }}"
        log_start: "{{ item.log_start }}"
        log_end: "{{ item.log_end }}"
      loop: "{{ firewall_rules.results }}"
      register: rule_results

    - name: Print rule creation results
      debug:
        msg: "Rule {{ item.name }} creation: {{ item.changed }}"
      loop: "{{ rule_results.results }}"