---

- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    palo_provider:
      ip_address: '10.10.10.1'
      username: 'admin'
      password: 'tttttt'

  tasks:
    - name: Create Server Object
      panos_address_object:
        provider: '{{ palo_provider }}'
        name: 'server1'               
        value: '172.16.1.10'                
        description: 'vmware'